title: Katrina and Tim 2020
description: Everything You Need for the Wedding of Katrina and Tim
sitename: Katrina & Tim's Wedding Website
baseurl: '/katandtim2020'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
